name: jwt
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  crypto: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
