name: server
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  sqleto: ^0.0.5+6

  jwt:
    path: ../packages/jwt

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  sqleto_generator: ^0.0.3+5
  build_runner: ^2.3.3
